### ISSUE TITLE
[Bug]: * isn't the first field in SELECT statement after extending by `selectRaw()`

### ISSUE THREAD

**Issue by CupNoodles** [ryanmitchell/ti-ext-reports#13]
### What happened?

https://github.com/ryanmitchell/ti-ext-reports/blob/master/controllers/Builder.php#L145 adds a `*, ` as part of a `selectRaw()`  to the query, which is sort of OK until you add an extension that *also* listens to `thoughtco.reports.extendQuery`. If you were to add something like 

```
Event::listen('thoughtco.reports.extendQuery', function($controller, $query, $modelName) {
        $query->selectRaw('DATE_FORMAT(order_date, "%Y-%m-%d") as order_date_formatted');
    }
});
```

then the second raw statement gets inserted _before_ the `*`, leading to a mysql error. The query in question is pretty complex but you can test the error (I had never seen this before) with 

```
mysql> select 1, * from ti_orders limit 1;
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '* from ti_orders limit 1' at line 1
mysql> select *, 1 from ti_orders limit 1;
// this executes successfully
```

### What did you expect to happen?

I don't know if there's clever Laravel tricks to ensure the ordering of the select elements (and haven't been able to google it due to the prevalence of tutorials for `orderBy`), but a quick fix is just to remove the `*` - other, better solutions would be welcome. 

### Version

TI 3.2.0 Reports 2.0.2

**Comment by ryanmitchell** [comment]
Maybe add $query->select('*') after this line?
https://github.com/ryanmitchell/ti-ext-reports/blob/10108083dd41b9cda88842d07d2cac34fa0a1da9/formwidgets/ReportsTable.php#L22

**Comment by CupNoodles** [comment]
Just tried it - it works until you select for either category or menu, but if you do then fails the aggregation query with something like `Column already exists: 1060 Duplicate column name 'order_id'` due to both `orders` and `order_menus` tables having an `order_id` column.

I think it'll be something like 

a.) remove the `*, ` from Builder.php
b.) add  `$query->select('orders.*')` to afer L22 in ReportsTable.php
c.) under the `thoughtco.reports.fieldToQuery` section of Builder.php, add a `$query->select('order_menus.*')` any time we add a join

https://github.com/ryanmitchell/ti-ext-reports/compare/master...CupNoodles:dk/query_extendability?expand=1

Unfortunately the branch above doesn't work if you have both menu and category as WHERE conditions since it'll try to join the table twice (I think this is a bug in the original ext though, lemme know if you want a separate issue opened for it).

**Comment by ryanmitchell** [comment]
I pushed some changes [here](https://github.com/ryanmitchell/ti-ext-reports/commit/3f5e00840922afd6f303fdcb588de6f21cb53d21). Does this solve it for you?

**Comment by CupNoodles** [comment]
Almost - https://github.com/ryanmitchell/ti-ext-reports/commit/3f5e00840922afd6f303fdcb588de6f21cb53d21?w=1#diff-1b267010dc9dbc97d4291c9fbe3e18db7a1952235d5c890a22ae72d766abb962R152 can't be a `selectRaw()` or else you'll get `SQLSTATE[42S02]: Base table or view not found: 1051 Unknown table 'tastyigniter.orders'` (`$tableName` doesn't have db a prefix).

It also doesn't solve the duplicate table issue if you have both category and menu item in the filters (admittedly a pretty small use-case). The two joins either need to be aliased differently or the PHP needs to check if the table's already been joined through `$query->getQuery()->joins` or something.

**Comment by ryanmitchell** [comment]
Odd I would expect getTable() to return the name with the prefix.

I’ll look into it next week when I’ve more time but feel free to open a PR with changes required if you can.

**Comment by ryanmitchell** [comment]
Give this a go: https://github.com/ryanmitchell/ti-ext-reports/commit/f5e510c301b44cbf9ccaec979235872a8fa12dc7

**Comment by CupNoodles** [comment]
Thats the one! Fixes both of the issues I've run into on this thread, closing. Thanks so much for the fixes!

**Comment by ryanmitchell** [comment]
Great, tagged 2.0.3 with these changes
